{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder-test-api",
    "version": "8.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "builder-test-api-8.7.0.jar",
          "url": "builder-test-api-8.7.0.jar",
          "size": 15329,
          "sha512": "8b5341cca19f672d30c697b9e85466f7829381d6e42f0292fda78ea338053762fa7ac9a2a29fb2943d8934fa7b8fb6d984f7390c82031defe1b18267dd76aca4",
          "sha256": "c32506113d10a5196b5e3f869802722c8f228c123086c04852f866cdf78c050d",
          "sha1": "27d2749d868ec3e16dce3f687801435cb17f62ca",
          "md5": "00c5e3337abb4dd02c1b3568b1d73e2c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "31.7.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "31.7.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.7.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.0.1-jre"
          }
        }
      ],
      "files": [
        {
          "name": "builder-test-api-8.7.0.jar",
          "url": "builder-test-api-8.7.0.jar",
          "size": 15329,
          "sha512": "8b5341cca19f672d30c697b9e85466f7829381d6e42f0292fda78ea338053762fa7ac9a2a29fb2943d8934fa7b8fb6d984f7390c82031defe1b18267dd76aca4",
          "sha256": "c32506113d10a5196b5e3f869802722c8f228c123086c04852f866cdf78c050d",
          "sha1": "27d2749d868ec3e16dce3f687801435cb17f62ca",
          "md5": "00c5e3337abb4dd02c1b3568b1d73e2c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-test-api-8.7.0-javadoc.jar",
          "url": "builder-test-api-8.7.0-javadoc.jar",
          "size": 117213,
          "sha512": "40dfffe24e8b56b9f6e0818cf9e580e92b78f9bd621813b619f210c209bfea2e4ba38bb38d028ae472a1d3043d7c80e229dfb38dffa374b96530114cb4e4932e",
          "sha256": "c624e27ccb62813686312139cbef559b2d6a80c824e7e30165d7a15e0902d56f",
          "sha1": "61ac81dbf7fa91d270c225df082f5dc8580ca077",
          "md5": "ab0c65f2022c4359705fb2042591540e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-test-api-8.7.0-sources.jar",
          "url": "builder-test-api-8.7.0-sources.jar",
          "size": 13848,
          "sha512": "cf9ba278366bc38499dc53033ce38455c63bf57125b13353ed5fb3b95d733faffd27620e02feafd10fb5660a67becd9c0374cf5e2c89d2471e86f95fd996a8f8",
          "sha256": "fe02bbd25dee1a64a4717cba0bf990e8ae28eefbbc61340206d142bc89b9fc04",
          "sha1": "28583b2b9bd9a82f2503a7b441d735291dadfca9",
          "md5": "4b9572bbb7a725c86a315809e14f97ab"
        }
      ]
    }
  ]
}
