{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle-api",
    "version": "8.7.0-alpha08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.6"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-api-8.7.0-alpha08.jar",
          "url": "gradle-api-8.7.0-alpha08.jar",
          "size": 348422,
          "sha512": "1be6da08ff4a0ca15a6aa40f9f1a1d0c185ce0b73695ace699dab76d46816cd9099a35215fe9cc6d81dc7470c380d5d8f037e5d5e77d4aa27968611d650127a9",
          "sha256": "f1f0a54a9c4d077f92318748290a3ea23667d7ee3581df5aef68a65e518ded54",
          "sha1": "14222712900249855ac9063b0d6bcc1189ed0c48",
          "md5": "a842204fe7b6720a8e072614834260f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "8.7.0-alpha08"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.0.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.6"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-api-8.7.0-alpha08.jar",
          "url": "gradle-api-8.7.0-alpha08.jar",
          "size": 348422,
          "sha512": "1be6da08ff4a0ca15a6aa40f9f1a1d0c185ce0b73695ace699dab76d46816cd9099a35215fe9cc6d81dc7470c380d5d8f037e5d5e77d4aa27968611d650127a9",
          "sha256": "f1f0a54a9c4d077f92318748290a3ea23667d7ee3581df5aef68a65e518ded54",
          "sha1": "14222712900249855ac9063b0d6bcc1189ed0c48",
          "md5": "a842204fe7b6720a8e072614834260f1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-api-8.7.0-alpha08-javadoc.jar",
          "url": "gradle-api-8.7.0-alpha08-javadoc.jar",
          "size": 151132,
          "sha512": "31f87f8f0b8e1df23836960f457d729ed4209dd920817661ab4e7b6b9c85ad16197a5b28c6b802c2404bcd453f459de5c0f5b3defeaa16628d3a6f7fb3fe7240",
          "sha256": "367c085f84ab7735f291b242a07c3f9aa572e2c5b63ec6e21c95a4309a223afb",
          "sha1": "acf189f15a241af74de43d5b33a3b13decb9b9da",
          "md5": "8abd8a20ba003dd409864a2472a10da4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-api-8.7.0-alpha08-sources.jar",
          "url": "gradle-api-8.7.0-alpha08-sources.jar",
          "size": 349144,
          "sha512": "c3895541b508002103968efe70c6c6035c4887705b21ee871e8ad7e6a560fa11d4e8515c19b6708a9101fdbc68acaec14f91b84c0f581ea3fce7d9c2e02baf49",
          "sha256": "b1280c335f72ec173da2b1cb0cdb5c310e20912bf0e1a2817bd3d8e5d7ba855c",
          "sha1": "c44927e6586e3ce0a30f7d210f9235c68eadb2e9",
          "md5": "be8b488b5fb89b4702c0ed09b7b41e32"
        }
      ]
    }
  ]
}
