{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle-settings-api",
    "version": "8.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.7.0.jar",
          "url": "gradle-settings-api-8.7.0.jar",
          "size": 9836,
          "sha512": "2e850a8227a96e786afe53dd97cdf45ae250b523f19f3c3a2d9c371097269041d65628c1dca71f6bc89ca4142a3f931d47468aba59244fa00147f63c928a23e5",
          "sha256": "7ddfc77332dee3585243152238ff00ac47b1707a419c0f1448453a0498fb6836",
          "sha1": "685c7792865081f91fb3046c804f096c49dc7913",
          "md5": "66549fc4411f133dfc980291bea681dd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-settings-api-8.7.0.jar",
          "url": "gradle-settings-api-8.7.0.jar",
          "size": 9836,
          "sha512": "2e850a8227a96e786afe53dd97cdf45ae250b523f19f3c3a2d9c371097269041d65628c1dca71f6bc89ca4142a3f931d47468aba59244fa00147f63c928a23e5",
          "sha256": "7ddfc77332dee3585243152238ff00ac47b1707a419c0f1448453a0498fb6836",
          "sha1": "685c7792865081f91fb3046c804f096c49dc7913",
          "md5": "66549fc4411f133dfc980291bea681dd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.7.0-javadoc.jar",
          "url": "gradle-settings-api-8.7.0-javadoc.jar",
          "size": 261,
          "sha512": "7414c2478ded003e92a0db13a541590a720150079c0b9602d9129a864704191aa5c75d9e6a667d9668e4d3fc39b664e502a8bb1d890f201d3333b2a08e7df135",
          "sha256": "73df962cd96efacadcef95a8a508d581e9cbb573054a7af3affcda37ab6f4d01",
          "sha1": "225cedfb545048a22b398455a7bfa45f6d2cc0be",
          "md5": "f7e9bc71faa60dc1f3aabc68edee4d39"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.7.0-sources.jar",
          "url": "gradle-settings-api-8.7.0-sources.jar",
          "size": 9407,
          "sha512": "5ac52c0be0758c11f62631a9a5c8d4b159dd3466cb574a92b9e1ecadd5afdbbc1a808002ec56c9075f0c8fb212e67585a6cdce93e752174f8c09be4a76b11da5",
          "sha256": "1bacbad7055765f5dbb734e363b6952d4970219dbbda20ec8200221a3ff71ea2",
          "sha1": "54163d836a9dd855142a9703b06a8232e77307ea",
          "md5": "8a058d272220dd3aab42cbaf97e9e60a"
        }
      ]
    }
  ]
}
