{
  "formatVersion": "1.1",
  "component": {
    "url": "../../foundation-layout/1.6.6/foundation-layout-1.6.6.module",
    "group": "androidx.compose.foundation",
    "module": "foundation-layout",
    "version": "1.6.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.6"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-layout-release.aar",
          "url": "foundation-layout-android-1.6.6.aar",
          "size": 526512,
          "sha512": "e079496fd9083bdbeec660f1d9231c8891e624f1ab90166f799c33c5fc32fa2648c055f16103e71dc45cad2863ebf3fbfa3e6891d4b4259cedfb23d7958d5310",
          "sha256": "e14b1bceb8e97a9c2bd6fe733d0da25e51bcf588d96199dcf1d06d36e851903b",
          "sha1": "b602cadc644d76fe25bd5d5ba45f7dccf90bb922",
          "md5": "d5b2c89262567774821594dfcdf962f5"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.6"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.6"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.6"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.7.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-layout-release.aar",
          "url": "foundation-layout-android-1.6.6.aar",
          "size": 526512,
          "sha512": "e079496fd9083bdbeec660f1d9231c8891e624f1ab90166f799c33c5fc32fa2648c055f16103e71dc45cad2863ebf3fbfa3e6891d4b4259cedfb23d7958d5310",
          "sha256": "e14b1bceb8e97a9c2bd6fe733d0da25e51bcf588d96199dcf1d06d36e851903b",
          "sha1": "b602cadc644d76fe25bd5d5ba45f7dccf90bb922",
          "md5": "d5b2c89262567774821594dfcdf962f5"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-layout-android-1.6.6-sources.jar",
          "url": "foundation-layout-android-1.6.6-sources.jar",
          "size": 79330,
          "sha512": "4590692fa450bb0efddf0ed46ecb7b32f3503e8f14fd97901e09d9c10218fa47f8c91524b3afc00ac5c7e414de9b2b70a470fbca9bc0d05a5a3b46751a61aa28",
          "sha256": "1e6b08fba6647fa32f94fa8ff6337b565cc0158e395e1654ec05083eecc6f1eb",
          "sha1": "7abc26bf88267a59649360c2e68a13d69976ff17",
          "md5": "cfb53bdca64405f84c4c6d6902d43241"
        }
      ]
    }
  ]
}