{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-tooling-preview/1.6.6/ui-tooling-preview-1.6.6.module",
    "group": "androidx.compose.ui",
    "module": "ui-tooling-preview",
    "version": "1.6.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.6"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-tooling-preview-release.aar",
          "url": "ui-tooling-preview-android-1.6.6.aar",
          "size": 17210,
          "sha512": "cf952effb37a58afea6ecc7822af7db9374a085211e2c59d52e6912c551449dc0a96abaeb480d60870f3e8aca1919cf345761b8a43a766ae63e34ca004b933fe",
          "sha256": "ea9a308839f87e1845af4662ef3cce2fa6f8cb2bb90c0a415d664a6ca4b3b951",
          "sha1": "a3f8dfd1ae373150922824ae793f5b985444f3c8",
          "md5": "04c70a97740b3eb4fbc639b87d8868dd"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.6"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-tooling-preview-release.aar",
          "url": "ui-tooling-preview-android-1.6.6.aar",
          "size": 17210,
          "sha512": "cf952effb37a58afea6ecc7822af7db9374a085211e2c59d52e6912c551449dc0a96abaeb480d60870f3e8aca1919cf345761b8a43a766ae63e34ca004b933fe",
          "sha256": "ea9a308839f87e1845af4662ef3cce2fa6f8cb2bb90c0a415d664a6ca4b3b951",
          "sha1": "a3f8dfd1ae373150922824ae793f5b985444f3c8",
          "md5": "04c70a97740b3eb4fbc639b87d8868dd"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.6.6"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-tooling-preview-android-1.6.6-sources.jar",
          "url": "ui-tooling-preview-android-1.6.6-sources.jar",
          "size": 11399,
          "sha512": "38560bdd4d5584a75a81b34fcc5cfd97ba6611d19fb9112b58e500aa87d6aae15c789c1edb99a8233df3337a2079c1e6f2e0161375136e069aa7863f7e6edd3c",
          "sha256": "656eba588959145bdea9b2bd67fe5c7a3ae685093ed69491d64698c81a70faa7",
          "sha1": "c1cc66505a91b370b6f456d88ab4eba3400300f7",
          "md5": "cb00e2d6aefd162943639320f8dfcd8e"
        }
      ]
    }
  ]
}