{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "aaptcompiler",
    "version": "8.7.0-alpha08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "aaptcompiler-8.7.0-alpha08.jar",
          "url": "aaptcompiler-8.7.0-alpha08.jar",
          "size": 499730,
          "sha512": "f19dfda44c794b5cd0116926b1a82286b8632b4e04b7f927a800da71634994d508e560c558ce97fdc6056ba5a5949cf043d2902c6933098aa4379639d4a3c0b5",
          "sha256": "8a45ef2be6bc2ed8f70983a48bcc51c88e5546ba7ed6eacb395af173da6ecb9b",
          "sha1": "1ddb34a8c5a0f8dfb8739f19aff506d459286405",
          "md5": "833f5759ea4e845c89a3041bd92c9d11"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "aapt2-proto",
          "version": {
            "requires": "8.7.0-alpha08-12006047"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.7.0-alpha08"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.7.0-alpha08"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.22.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.0.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "aaptcompiler-8.7.0-alpha08.jar",
          "url": "aaptcompiler-8.7.0-alpha08.jar",
          "size": 499730,
          "sha512": "f19dfda44c794b5cd0116926b1a82286b8632b4e04b7f927a800da71634994d508e560c558ce97fdc6056ba5a5949cf043d2902c6933098aa4379639d4a3c0b5",
          "sha256": "8a45ef2be6bc2ed8f70983a48bcc51c88e5546ba7ed6eacb395af173da6ecb9b",
          "sha1": "1ddb34a8c5a0f8dfb8739f19aff506d459286405",
          "md5": "833f5759ea4e845c89a3041bd92c9d11"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aaptcompiler-8.7.0-alpha08-javadoc.jar",
          "url": "aaptcompiler-8.7.0-alpha08-javadoc.jar",
          "size": 81065,
          "sha512": "edfe26eb84751d3a82fe52500182d2d59647eddac08287011593de5100966bcb530d71d076b81d8aa0aff63ca1cba05e9c86951b1607b94981d57cc4e9370116",
          "sha256": "106fdf5a3ffd0daa984ff7405762387e1b54b6f14a0aa9073b8a20700e8163e8",
          "sha1": "79b7a594fc21ec5ae7c2403264f0fb27bb09595a",
          "md5": "a92d9ea7cdc8026ad8b69255b3922888"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aaptcompiler-8.7.0-alpha08-sources.jar",
          "url": "aaptcompiler-8.7.0-alpha08-sources.jar",
          "size": 152981,
          "sha512": "60648d9c9dd3ccc8c9b758e6b4a05732ed7e4d51f2f6c628c647adbc9580b79415d2e46bf506608ce491aeaa1fa64b49f33603a7baa40757c2b84871d997bf22",
          "sha256": "bd0d54e72f42e74d7784d17ef176005ebcf295faa060bdd5411c3580d65364dc",
          "sha1": "2324e614e8c3c47b6375bb1e2c9ce6d4a836bfaa",
          "md5": "956cbb57ca03b7799366467121ee5bc1"
        }
      ]
    }
  ]
}
