{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder",
    "version": "8.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.7.0"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.7.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.7.0.jar",
          "url": "builder-8.7.0.jar",
          "size": 15074474,
          "sha512": "96c14f794db6af4c627dcb6d3d9e67e651df3f45ad28883df9f9d4afec49812d0c8dfbd28b308166c7396f01233090d8cbb33d305b7856f46124eca39e2ebdaf",
          "sha256": "89b5beb3396a8b4529bccc653b321a9cd968e25245be3b1c320189759abb6edf",
          "sha1": "3e992622ed43bc1e386c996e1c13afcedd0a1854",
          "md5": "84e51b4bb2a82ad2de8d5733e198d5ec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "8.7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "8.7.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "31.7.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.7.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.7.0"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "31.7.0"
          }
        },
        {
          "group": "com.android",
          "module": "signflinger",
          "version": {
            "requires": "8.7.0"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "31.7.0"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "tracker",
          "version": {
            "requires": "31.7.0"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk18on",
          "version": {
            "requires": "1.77"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.77"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.7.0"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.7.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.7.0.jar",
          "url": "builder-8.7.0.jar",
          "size": 15074474,
          "sha512": "96c14f794db6af4c627dcb6d3d9e67e651df3f45ad28883df9f9d4afec49812d0c8dfbd28b308166c7396f01233090d8cbb33d305b7856f46124eca39e2ebdaf",
          "sha256": "89b5beb3396a8b4529bccc653b321a9cd968e25245be3b1c320189759abb6edf",
          "sha1": "3e992622ed43bc1e386c996e1c13afcedd0a1854",
          "md5": "84e51b4bb2a82ad2de8d5733e198d5ec"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.7.0-javadoc.jar",
          "url": "builder-8.7.0-javadoc.jar",
          "size": 346021,
          "sha512": "37a54d3919c810242babe694fa62355dc305b0ef7e94ec449d4d130cc5c16c0d2fc701bf6fb66376aafe8338527d4e6b2a4ae79c0ada29db3c2624f52682bdce",
          "sha256": "dc05b7ff063978e1390ac15281daffebbde20e7349600d24d9ae34dca0570485",
          "sha1": "55c9dbe1075041d0966696d35ee8ead65de61bbf",
          "md5": "34106c1d4d7bbd1126b4ae9d7b7a31f5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.7.0-sources.jar",
          "url": "builder-8.7.0-sources.jar",
          "size": 282773,
          "sha512": "c8379bd205e6b451889e4e1fcd72f5feaecda5dc8f4b01eacd744c9f3c41b95e0007c8498faf25defb84f2927824c4fcbca06e35089dd960c8815ba16554b0ec",
          "sha256": "ece134d73f5b9050bc0292f63977d82675fdf9a712fa12499de87cec1c4e59cf",
          "sha1": "2057c4a283b9aa3e9f8cb3094af9368e75492424",
          "md5": "b4fcba2145fa01a19a77fc77db1dfb37"
        }
      ]
    }
  ]
}
