{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle-api",
    "version": "8.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.6"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-api-8.7.0.jar",
          "url": "gradle-api-8.7.0.jar",
          "size": 349254,
          "sha512": "387523e5b89a48b826ca214eb8de25a8abd05e2a9b5c8e6cbfab67dbc78ad8678f6aa61610d4d2f35383cd9dd6571e10167169fdd3b75d606e6877a6ee3b9da9",
          "sha256": "09e441732c94c811b9f685d840edee4a986ee7b322e10abb6f0abdfd6c7c3382",
          "sha1": "5ca53415293e7c3ed526b2165767e45f81343822",
          "md5": "034c1aecae4f2a80815eb59d8021abfc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "8.7.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.0.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.6"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-api-8.7.0.jar",
          "url": "gradle-api-8.7.0.jar",
          "size": 349254,
          "sha512": "387523e5b89a48b826ca214eb8de25a8abd05e2a9b5c8e6cbfab67dbc78ad8678f6aa61610d4d2f35383cd9dd6571e10167169fdd3b75d606e6877a6ee3b9da9",
          "sha256": "09e441732c94c811b9f685d840edee4a986ee7b322e10abb6f0abdfd6c7c3382",
          "sha1": "5ca53415293e7c3ed526b2165767e45f81343822",
          "md5": "034c1aecae4f2a80815eb59d8021abfc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-api-8.7.0-javadoc.jar",
          "url": "gradle-api-8.7.0-javadoc.jar",
          "size": 151132,
          "sha512": "198ab3968217f81b114b065ca6c551b7765522ffd5ddcb1471e54d58dae56d900a0c6881119fa0531e81c582d8c43411b02a61c4f5b709c8e904c0e1193677cd",
          "sha256": "391e7aa3991b8af3a3d9c53d4dadcaf4fe70a6ab2155244da591ca1ed2063941",
          "sha1": "c4f0591f5d40b5b6ed81f70ecdfcbbbb57cfb610",
          "md5": "3c19b6a8bf08877b4bbefc02b89cc4cf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-api-8.7.0-sources.jar",
          "url": "gradle-api-8.7.0-sources.jar",
          "size": 349674,
          "sha512": "9579ca97cb1e6f15bcf57662bc6c58de433595b747f4f872a54d42c9e59040cbf0b58527944cead9d0fdb0aa7705697eb011ceaaebfc8a4853c49ea3c84aea85",
          "sha256": "1fd8c4c239188f545cc5b5dca8751811ae96b9f9e5dec70fc71a9d54894a2552",
          "sha1": "2e2b98d6f2e22bd4beb0adc3eb5f4161c0fad0fe",
          "md5": "2d378f8db38b4f9e792969e94c7ea7fc"
        }
      ]
    }
  ]
}
