{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle-settings-api",
    "version": "8.7.0-alpha08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.7.0-alpha08.jar",
          "url": "gradle-settings-api-8.7.0-alpha08.jar",
          "size": 9836,
          "sha512": "b029cf0c1a30f0399a750348597de2ee4b00d0a1be5f1118b816ab500e3f8ef4891208e5f5b4ccd77a4dca26b357687e6bd11607addb2076d08f7d6ff9ffe7d2",
          "sha256": "b721ad24636be9a5d67da3584752c4a27be076d55bb1ebd6d93b902eb3b6b1fb",
          "sha1": "7da772c1343c9eb03631cb01bbf85f11f31e5774",
          "md5": "4c3b96aee503fadad3ef8fc90058c88e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-settings-api-8.7.0-alpha08.jar",
          "url": "gradle-settings-api-8.7.0-alpha08.jar",
          "size": 9836,
          "sha512": "b029cf0c1a30f0399a750348597de2ee4b00d0a1be5f1118b816ab500e3f8ef4891208e5f5b4ccd77a4dca26b357687e6bd11607addb2076d08f7d6ff9ffe7d2",
          "sha256": "b721ad24636be9a5d67da3584752c4a27be076d55bb1ebd6d93b902eb3b6b1fb",
          "sha1": "7da772c1343c9eb03631cb01bbf85f11f31e5774",
          "md5": "4c3b96aee503fadad3ef8fc90058c88e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.7.0-alpha08-javadoc.jar",
          "url": "gradle-settings-api-8.7.0-alpha08-javadoc.jar",
          "size": 261,
          "sha512": "6a693d55a998a3ae6e03130e6f2bb86d9857fb4fbf885fc3954f07e762e4037796e9c7dfaee98db4d2accd151ecff8d2f13fea124393f0a083b499bdbf4ac2a8",
          "sha256": "a21e01f4acbe80ff1bac5d86b64162eb675f0d018f6bf8f4c0581daa743ea8c4",
          "sha1": "e652c480fdafee8679054a1b1ddb60a4558cd59b",
          "md5": "8ae81ebae45d4ebd01b12b684bbb7ff1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.7.0-alpha08-sources.jar",
          "url": "gradle-settings-api-8.7.0-alpha08-sources.jar",
          "size": 9407,
          "sha512": "694e814076440fe39fb573d93332a1c8cad24b08461eaccf1fde3c45e8f8ef7df98367533d43561e429fb8196ecc1f0813855f24ea3a2b5acd04a8da852aae37",
          "sha256": "464e02b9be92af43db430f46310b64636d3e7d6ad19bb14323676f807cfabd67",
          "sha1": "2af84f0b7591e49c56ec43a06f952e948b71c8d7",
          "md5": "14fa487349202d39f2f226f61518a5c4"
        }
      ]
    }
  ]
}
