{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "aaptcompiler",
    "version": "8.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "aaptcompiler-8.7.0.jar",
          "url": "aaptcompiler-8.7.0.jar",
          "size": 499730,
          "sha512": "21efd25922b49a94e953da9f9640d1dba7f5cf583880848bc22d71010950ea34d69d32843b2656defff1b658d0bb92d31f055eaafe36ae6f74b51d8b69f95702",
          "sha256": "ea4a886009444435f7a19fcaede1eaf180e8d85145f7c52a4ba87cbc356c563a",
          "sha1": "89976d4ba1c9c21a758571c824ee867190647800",
          "md5": "29d248ba77c79fa7d64a53cfd7b44211"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "aapt2-proto",
          "version": {
            "requires": "8.7.0-12006047"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.7.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.7.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.22.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.0.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "aaptcompiler-8.7.0.jar",
          "url": "aaptcompiler-8.7.0.jar",
          "size": 499730,
          "sha512": "21efd25922b49a94e953da9f9640d1dba7f5cf583880848bc22d71010950ea34d69d32843b2656defff1b658d0bb92d31f055eaafe36ae6f74b51d8b69f95702",
          "sha256": "ea4a886009444435f7a19fcaede1eaf180e8d85145f7c52a4ba87cbc356c563a",
          "sha1": "89976d4ba1c9c21a758571c824ee867190647800",
          "md5": "29d248ba77c79fa7d64a53cfd7b44211"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aaptcompiler-8.7.0-javadoc.jar",
          "url": "aaptcompiler-8.7.0-javadoc.jar",
          "size": 81065,
          "sha512": "8bb93cf66d42fec3e3fa7c7daea72d8d8f7dc3f192977a22d93b2d1a2dcd00440f4977c8ba0b8cefdc5afda5b705b227ca6f3a424951ca9a980e68f412928efa",
          "sha256": "361a334b7f072789e0711b047ca12fafc74dae81c90387df1718ead54112077b",
          "sha1": "cefdbc1243158e02b5fa3d259de6dd267f6960f8",
          "md5": "73b9f2f6d0781639ac39977d2c4deb9f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aaptcompiler-8.7.0-sources.jar",
          "url": "aaptcompiler-8.7.0-sources.jar",
          "size": 152981,
          "sha512": "837d9ee4a92eaf03b93e6e3645474d13782194dea366c46119e4fe3d654de6c7cd7d3722b57a9521c25cf516305c7412184ccc46f3b8965521b3e297f4f8e6a4",
          "sha256": "23b27da43588a527ef6209de25d251debed9b1086eb54592ffda8bb61c20d89a",
          "sha1": "8fa18a52c67c87c1082dd4d5621484e2f32cbed2",
          "md5": "e6cc1f8eea7c946fd897062c46cb4122"
        }
      ]
    }
  ]
}
