{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.core",
    "module": "core-ktx",
    "version": "1.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-ktx-1.12.0.aar",
          "url": "core-ktx-1.12.0.aar",
          "size": 173700,
          "sha512": "999a6f12b60a3c140e8183f83e001b9d7c6a511fbeaeb6faf1cd31cbb6953758ed758d10e054472f64cdb7ab3d396bb8489a3ced56458e5be1401d705438075c",
          "sha256": "95b3edaf78227b7cc8d802d11f8793a9aed292e52b8fbf8c08d6134ccb1716d3",
          "sha1": "1b80a40d6f34eb52c8de87c186feb57aa2a43ada",
          "md5": "1ff45cd37d0e3043b5862742fc9a931c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ktx-1.12.0.aar",
          "url": "core-ktx-1.12.0.aar",
          "size": 173700,
          "sha512": "999a6f12b60a3c140e8183f83e001b9d7c6a511fbeaeb6faf1cd31cbb6953758ed758d10e054472f64cdb7ab3d396bb8489a3ced56458e5be1401d705438075c",
          "sha256": "95b3edaf78227b7cc8d802d11f8793a9aed292e52b8fbf8c08d6134ccb1716d3",
          "sha1": "1b80a40d6f34eb52c8de87c186feb57aa2a43ada",
          "md5": "1ff45cd37d0e3043b5862742fc9a931c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ktx-1.12.0-sources.jar",
          "url": "core-ktx-1.12.0-sources.jar",
          "size": 69935,
          "sha512": "4a8ebde3422930919392c5000cb86ea1e7182181e32db767a14de7c21b15b4793bd54f593ccaf85dde063eefc85a80fe77cf159c78c446b508ca472c28a45135",
          "sha256": "0c6d6a21f2cc8def077ab9443a150fa898744d42084f4a29d459b8b00c1b957e",
          "sha1": "e6c10584acda1ffeb12bf3bee451bed5ffbe2705",
          "md5": "dfaa8f67c21aed2aae477ce539e41ad4"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "core-ktx-1.12.0-versionMetadata.json",
          "url": "core-ktx-1.12.0-versionMetadata.json",
          "size": 42717,
          "sha512": "d94e7af20884072ba66f3e89dbd1b4e1823156d64bae821674229d47b5a48aa8d552ab42628b5a4d51286814390f8bf4a848006c3653a783e1d324ac6e643eea",
          "sha256": "261dcd3c8616cae91271d5163997c45b8b509af204786420649a0b7e0f245281",
          "sha1": "9ccd1b46b95778109472c0a16ddd08e4bef021f0",
          "md5": "e320a403a93dad70e1c5d328f07a9e93"
        }
      ]
    }
  ]
}