{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder-model",
    "version": "8.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "builder-model-8.7.0.jar",
          "url": "builder-model-8.7.0.jar",
          "size": 125147,
          "sha512": "17ff3cdf9ede637f12f747d4c15e12b26babd4193786a2b5df1f5529050ed9581d71560ca9f97920eb3c4251a6ea0882f144f123ecd3488a556db5a46fa3f1e7",
          "sha256": "a96dc78cf39b4e569de90e8150b5efa66642d25908caf2890c603cc647a16c78",
          "sha1": "a5b8da9ab17f9dcbe3d39eec0081aa9786e88637",
          "md5": "327302c97680bfc6747cde8c26ac6378"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "31.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "builder-model-8.7.0.jar",
          "url": "builder-model-8.7.0.jar",
          "size": 125147,
          "sha512": "17ff3cdf9ede637f12f747d4c15e12b26babd4193786a2b5df1f5529050ed9581d71560ca9f97920eb3c4251a6ea0882f144f123ecd3488a556db5a46fa3f1e7",
          "sha256": "a96dc78cf39b4e569de90e8150b5efa66642d25908caf2890c603cc647a16c78",
          "sha1": "a5b8da9ab17f9dcbe3d39eec0081aa9786e88637",
          "md5": "327302c97680bfc6747cde8c26ac6378"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-model-8.7.0-javadoc.jar",
          "url": "builder-model-8.7.0-javadoc.jar",
          "size": 291474,
          "sha512": "61a27ed257be25516bafc1a869d9e13da352949937393c42087c197f1377199542068af7e5517ce18f75c377ca628a65a8e96307df8f1c0618eda9bf98678cfb",
          "sha256": "2dfce097733a62901df2996f3b8a0296635c7fba4a75c2ac21ccffb5da1f4466",
          "sha1": "6aebf480777171ed479ac55abe79670233ae2f63",
          "md5": "2376aa56ace4dbf5c61b94d62f097cee"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-model-8.7.0-sources.jar",
          "url": "builder-model-8.7.0-sources.jar",
          "size": 145555,
          "sha512": "1cd5639885382e6258f8d2f2704963986bcb9fcf1b9dd08bddec3b2cecd237d05efa54ae14aad8e4d4f5e7951b597f140f067e8d63a140570d643b3a8b6db29f",
          "sha256": "89b9e4713a7b1bd8ce2e2f65552a2d6b332b4f4802414d9ae67e1382ef38922d",
          "sha1": "798fe3e5489250a1715ebe5e646b0088ce808327",
          "md5": "ecab3fa2f376d5ed286da53936c81c12"
        }
      ]
    }
  ]
}
