{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "aapt2-proto",
    "version": "8.7.0-12006047",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "aapt2-proto-8.7.0-12006047.jar",
          "url": "aapt2-proto-8.7.0-12006047.jar",
          "size": 711278,
          "sha512": "9e0ae53533cdb6f6dbc78ede146e32788ecc9ce3e5f87d870ae917e888e47ac75004e3d8c64b135a54179b908ad51e54b3936d88165f8146f0e32884e3d3953e",
          "sha256": "fe17ba3348a29f8c41922ccaff0cf54ef4407c3e77407a9f87c1e555a1734c90",
          "sha1": "0098413e854cd86e4e5ede40eb679947f4a85759",
          "md5": "1b673cb5111713215571dbb9e4759ffc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.22.3"
          }
        }
      ],
      "files": [
        {
          "name": "aapt2-proto-8.7.0-12006047.jar",
          "url": "aapt2-proto-8.7.0-12006047.jar",
          "size": 711278,
          "sha512": "9e0ae53533cdb6f6dbc78ede146e32788ecc9ce3e5f87d870ae917e888e47ac75004e3d8c64b135a54179b908ad51e54b3936d88165f8146f0e32884e3d3953e",
          "sha256": "fe17ba3348a29f8c41922ccaff0cf54ef4407c3e77407a9f87c1e555a1734c90",
          "sha1": "0098413e854cd86e4e5ede40eb679947f4a85759",
          "md5": "1b673cb5111713215571dbb9e4759ffc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aapt2-proto-8.7.0-12006047-javadoc.jar",
          "url": "aapt2-proto-8.7.0-12006047-javadoc.jar",
          "size": 1063962,
          "sha512": "444279a2f7f107cb1ac846e3fa2ac2357bbc6081c8a88b8a7c797b4ebdf4ca787a662600d1e04f565da2aedb43984ff279084bfbfed37ef3ea3c96d90be98b63",
          "sha256": "c6a3798b8b85b7393fc7c24edc3e558382176244b3bc5c6418da8605962b6a8f",
          "sha1": "b95c29af276056dd19500229a5060572b4287e09",
          "md5": "0c05502e320b94af4b78cac5b93d1d18"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aapt2-proto-8.7.0-12006047-sources.jar",
          "url": "aapt2-proto-8.7.0-12006047-sources.jar",
          "size": 394856,
          "sha512": "f895395f9446b9b7a699ad1509eb5c7ffc689f04e6bd1d0e9d7df4489991dfe90b7a2de96be6f30bbd5ec5aa3d013e0434409bb18b7a5c4a261fb9f4f9efba46",
          "sha256": "d703d3bd02eddcf413fadc9f691f465c33ff3a03db6b02998e5ced9516c66cf0",
          "sha1": "3084c90a2e265812ce3057708bf7597f3a04636e",
          "md5": "03d0dada3f8075e16f3881d1177b0b4e"
        }
      ]
    }
  ]
}
