{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.constraintlayout",
    "module": "constraintlayout-compose",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "constraintlayout-compose-1.0.1.aar",
          "url": "constraintlayout-compose-1.0.1.aar",
          "size": 334386,
          "sha512": "1254fc2b3d88d94787e626e5856170f0b16a8444591e74ab2154dd72cbdac053dcda290db34e3ffc73c790e5791c56cf4abfac05d5b16baf28cd4c1b449184aa",
          "sha256": "75000f2eeeddf0f602c0673a7d182b4ff769f44b6359b6fd88b48951d5fb2661",
          "sha1": "31d3f17a1a37077c0f5a0138061e3e4dfd39dcf7",
          "md5": "e7ddb219dc020cdd50211a0f55a03089"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-core",
          "version": {
            "requires": "1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "constraintlayout-compose-1.0.1.aar",
          "url": "constraintlayout-compose-1.0.1.aar",
          "size": 334386,
          "sha512": "1254fc2b3d88d94787e626e5856170f0b16a8444591e74ab2154dd72cbdac053dcda290db34e3ffc73c790e5791c56cf4abfac05d5b16baf28cd4c1b449184aa",
          "sha256": "75000f2eeeddf0f602c0673a7d182b4ff769f44b6359b6fd88b48951d5fb2661",
          "sha1": "31d3f17a1a37077c0f5a0138061e3e4dfd39dcf7",
          "md5": "e7ddb219dc020cdd50211a0f55a03089"
        }
      ]
    }
  ]
}
